# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Amce-CNA
version:      0.01
version_from: lib/Amce/CNA.pm
installdirs:  site
requires:
    Class::ISA:                    0
    Sub::Exporter:                 0.96

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
