--- #YAML:1.0
name:               Amce-CNA
version:            0.065
abstract:           a moer tolernat verison of mehtod location
author:
    - Ricardo SIGNES <rjbs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::ISA:     0
    Sub::Exporter:  0.96
resources:
    Repository:  http://github.com/rjbs/amce-cna
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
